### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by pirate-zhang** [wangguanzhi/LADN#10]
When i  try to train this model ,it get error like this:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

 does somobody getting this same error?can you figure it out?

thanks a lot~

**Comment by georgegu1997** [comment]
Thanks for reaching out! Could you please share the version of PyTorch, OS, CUDA you are using? 

And could you try `conda env create -f environment.yml` and re-run the script?

**Comment by Jeffin-x** [comment]
> When i try to train this model ,it get error like this:
> 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> does somobody getting this same error?can you figure it out?
> 
> thanks a lot~

I also have such a problem. Have you solved it

**Comment by Jeffin-x** [comment]
> When i try to train this model ,it get error like this:
> 
> RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [128]] is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
> 
> does somobody getting this same error?can you figure it out?
> 
> thanks a lot~

 I use the environment you provide and I also have such a problem. How to solve it? Thanks.

**Comment by wangguanzhi** [comment]
Please see https://github.com/wangguanzhi/LADN/issues/7.
