### ISSUE TITLE
测试效果

### ISSUE THREAD

**Issue by summerwbb** [wangguanzhi/LADN#3]
你好！非常感谢分享您的思想并且公开code！
我运行了您的测试程序，但是感觉妆容很脏，我是安装您的git指导运行的，请问有什么需要注意的吗？
![image](https://user-images.githubusercontent.com/40291885/69716915-08b9d200-1146-11ea-9a7f-5e0bdd011518.png)

**Comment by wangguanzhi** [comment]
您好，非常感谢您对我们工作的关注。我们刚刚更新了test的sample commands，对于light.pth, 可以在后面加上 --no_extreme 来除掉extreme makeup，对于extreme.pth, 可以在后面加上 --extreme_only, 只保留extreme makeup。我们目前的模型对于source image (before makeup)和 reference image (after makeup) align程度较高的结果表现相对较好，所以对于align程度较低的部分数据就有可能出现妆容较脏的情况，这是我们工作limitation之一。对于人脸的alignment，我们没有做过多的处理，我们相信更好的alignment的方法可以提升网络的表现，作为未来本领域的方向。
