### ISSUE TITLE
test时程序一直卡住

### ISSUE THREAD

**Issue by wwq66** [wangguanzhi/LADN#4]
在使用light.pth测试时，程序卡在`ep0, total_it = model.resume(opts.resume)`中，具体是卡在`getattr(self, 'dis'+local_part.capitalize()).load_state_dict(checkpoint_backup['dis'+local_part.capitalize()])`处。想问下这是正常的吗，该如何解决

**Comment by zhangbaijin** [comment]
你好，请问你的问题解决了吗，我测试的时候也是一直卡住，`-- load dataset ---
Dataset for training A: 334, B: 278 images
API landmarks loaded successfully!
creating dataset_test
Using random sampled points for test_forward
Dataset for testing initialized, including 300 data points
API landmarks loaded successfully!

--- load model ---
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
initialize network with normal
`
