### ISSUE TITLE
关于fake_AA_encoded和fake_A_random

### ISSUE THREAD

**Issue by wwq66** [wangguanzhi/LADN#5]
能解释下代码中这两个生成图的含义吗，不是很理解他们的作用。十分感谢~

**Comment by wangguanzhi** [comment]
您好！对于 fake_AA_encoded 和 fake_A_random 的作用，可以参考 [Diverse Image-to-Image Translation via Disentangled Representations](https://arxiv.org/pdf/1808.00948.pdf)。fake_AA_encoded 用于 self-reconstruction loss，fake_A_random 用于 latent regression loss。
