### ISSUE TITLE
landmark_file

### ISSUE THREAD

**Issue by huangzhikun1995** [wangguanzhi/LADN#8]
I want to test some new data that wasn't in your datasets, 
but I got an error message that the landmarks of new images are not in the 'landmark_file'.

I would like to ask you how do I generate 'landmark_file' for new data.

Thank you and looking forward to your reply.

**Comment by georgegu1997** [comment]
Please refer to [this repo](https://github.com/georgegu1997/makeup-transfer-public). You need to register for [Face++ Cognitive Services](https://www.faceplusplus.com/) and run the sample script in the README.
